### PR TITLE
Add Azure Pipelines support

### PR DESCRIPTION
**Pull request by wqweto**
This is an example of setting up Continuous Ingration on the project using [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) to compile, zip and upload `PhotoDemon-latest.zip` to repo's [Releases tab](https://github.com/tannerhelland/PhotoDemon/releases) after every commit to `master` branch. Additionally each PR is also checked whether the project compiles w/ changes applied. (Here usually unit tests are run if available too but still good.)

The config in `azure-pipelines.yml` has to be tweaked with proper repo name after Azure Pipelines is setup on main repo. You can check out https://github.com/wqweto/PhotoDemon/releases for a sample how the auto generated project's latest release looks like.

I'm running the compiling agent on a VM of mine so I'm not sure how the VB6 licenses pan out here. This has to be researched too but I'm willing to spare CPU cycles, no problem if you are willing to try it out.

### CODE REVIEW

**Comment by tannerhelland** [comment]
Wowowow @wqweto, this is very cool.  Thank you for sharing!  

I like the clever workaround of vb6.exe > logfile > findstr piped to stderr to produce a usable CI result.  This is the first elegant VB6 CI implementation I've seen.

Thank you for offering use of your VM.  I've just set up an agent on a local VM and will probably turn off PR-trigger compiling for now, due to relative rarity of PRs and (perhaps paranoid) security concerns.  If the VB6 community figures out git someday and I have PRs coming out my ears I can certainly revisit...   (heat death of the universe probably more likely to occur first)

BTW do you have source or license info for VBCodeLines.exe?  Actually, I may drop it either way as I use "Break on All Errors" for PD, so at present very few functions could use ERL intelligently.  I do like the concept of line numbers integrated into CI unit-testing strategy, though!

I will merge as-is and make necessary changes to the yaml after.  Thank you again 🙏

**Comment by Kroc** [comment]
VB6 CI??? That's a wee bit mental, and awesome! I never thought I'd see it.

**Comment by wqweto** [comment]
Wow, that was a fast merge! Glad you were able to sucessfully tweak the config YAML -- I spent couple of *days* to get my head around it and Azure Pipelines altogether. Had to abuse the "amend last commit" option before producing working `azure-pipelines.yml` without producing a ginormous (and somewhat shameful) list of same named commits :-))

Anyway, here is the VbCodeLines legacy project: https://github.com/wqweto/VbCodeLines  (Not very proud how it got implemented 15 years ago but it works so I had no need to revise it since then)

I'm using `Break on All Errors` in the IDE for all my projects too but still error logging at run-time with call-stack that includes `Erl` on *each* stack frame is very useful IMO but this depends on the kind of project I suppose and it needs tweaking to project-wise error handling routines to get implemented too.

**Comment by tannerhelland** [comment]
Of course, badges!  How could I forget the most critical part of CI??  😆 

Thank you for the reference markdown.  You've saved me so much time doing all the hard work on this Azure Pipelines stuff.  I never would have been ambitious enough to solve this on my own.

Thank you also for source to VbCodeLines.  I will star the repo for future investigation.

I see also a new PR - off to take a look now!

**Pull request merged**
