### PR TITLE
First attempt at a queue-based solution for accelerator handling.

### PR DESCRIPTION
**Pull request by jpbro**
Hi Tanner, as discussed in the following issue: https://github.com/tannerhelland/PhotoDemon/issues/243

For your review: This is my pull request on my first attempt at a queue-based solution for accelerator handling in PhotoDemon.

Hope it helps!

### CODE REVIEW

**Comment by jpbro** [comment]
Hi Tanner, I'll take a look at this now, thanks for the review!

**Comment by jpbro** [comment]
Hi Tanner, thanks again for the review - dropping the nCode check was my mistake.

I've made some changes to the way `CanIRaiseAnAcceleratorEvent` works that you will want to review. I now do the check in the `m_FireTimer_Timer` event and pass True to a new optional parameter that skips the active timer check.

Should I be creating a new pull request for the changes?

**Comment by tannerhelland** [comment]
> Should I be creating a new pull request for the changes?

No, this one is great!  I'll squash everything into a single commit anyway.

Thank you for those changes.  I think everything is ready to go...?  I'm gonna wrap up some existing work then get this merged.  I'm excited to test it!

**Comment by jpbro** [comment]
I _think_ everything is ready to go - things are working well in my testing here at least! Of course, if you find any problems let me know and I will get back to work :)

2 things to note:

* I left a comment in the original issue about how the second accelerator press of the very first rapid-fire accelerator sequence after startup fails. Subsequent sequences are working well though. 

* I'm not 100% sure that the handling in `CanIAccumulateAnAccelerator` is ideal. Right now I'm just testing if the main form is the active window here (are accelerators being used on other forms? Maybe I should be testing if the Parent window of the pdAccelerator control is the active window instead?

**Comment by tannerhelland** [comment]
> I'm not 100% sure that the handling in CanIAccumulateAnAccelerator is ideal. Right now I'm just testing if the main form is the active window here (are accelerators being used on other forms? Maybe I should be testing if the Parent window of the pdAccelerator control is the active window instead?

Thank you for mentioning this.  I think I'll make the check even simpler by just using:

CanIAccumulateAnAccelerator = (Not g_ModalDialogActive)

Global variables are obviously not ideal (and I'm working on removing as many as possible!) but in its present state, PD internally tracks when modal dialogs are active via that g_ModalDialogActive value.  It catches some edge cases that aren't easily detected otherwise, so it should take care of the check for us.

(And no, accelerators are not used on any other form... to my knowledge.  But the long-term plan is to move away from modal dialogs entirely, and instead reflect things like effect previews on the main window, so it's probably good to swap in a system other than GetActiveWindow() as future-proofing against future improvements.)

**Pull request merged**
