### PR TITLE
Added Japanese localization

### PR DESCRIPTION
**Pull request by hosiken**
Added Japanese localization.

I translated about 20% of it manually for short words, then did a batch translation at DeepL. After I reviewed the whole thing and manually corrected most of the puzzling translations and notational quirks, which are not perfect, but most of them are corrected.

I am currently reviewing it further, both visually and with Google Translate and ChatGPT GPT-4o, looking for unnatural or incorrect translations, and will review as much as possible during July 11 and I will lift the draft flag. 

See also #572

image

### CODE REVIEW

**Comment by tannerhelland** [comment]
I am ready to launch a new PhotoDemon stable release!  

Before release, I would like to double-check the new Japanese language file and ensure PhotoDemon's automatic language file updater works OK with it.  Let me know when you are ready to lift the draft flag and I will merge the new file ASAP so I can run a few final tests.

Thank you!

**Comment by hosiken** [comment]
Thank you for patience!
Once again, I have visually reviewed all the phrases and completed as many corrections as possible, so I have removed draft flag.
Best regards!

**Comment by tannerhelland** [comment]
Thank you so much, @hosiken !

I have added your name to the contributors list and will launch the new stable release shortly.  I am very excited to make your translation available to all.

**Comment by hosiken** [comment]
@tannerhelland
Thanks! But I'm very sorry, I found an error right after the merge and made the last correction again.
If you don't mind, please merge #574 🙇.

**Pull request merged**
